# 🟢 Lesson 02 — NumPy

**Level: Beginner** · Fast numeric arrays — the foundation of Pandas, SciPy, Rasterio and everything else.

*Part of the companion package for [python_for_geologists](https://github.com/kevinalexandr19/python_for_geologists) by Kevin Alexander Gomez.*

In [1]:
import numpy as np
print("NumPy", np.__version__)

NumPy 2.3.5


## 1. Arrays vs lists — vectorised math
Operations apply to *every element at once*, no loop needed.

In [2]:
cu_pct = np.array([0.79, 0.83, 1.20, 0.45, 2.10, 0.31, 1.75])

cu_ppm = cu_pct * 10000            # whole-array math
print("ppm:", cu_ppm)
print("mean %.3f | std %.3f | max %.2f" % (cu_pct.mean(), cu_pct.std(), cu_pct.max()))

ppm: [ 7900.  8300. 12000.  4500. 21000.  3100. 17500.]
mean 1.061 | std 0.614 | max 2.10


## 2. Boolean masking — apply a cutoff grade

In [3]:
cutoff = 0.5
mask = cu_pct >= cutoff
print("mask        :", mask)
print("ore grades  :", cu_pct[mask])
print("ore fraction: %.0f%%" % (100 * mask.mean()))
print("mean ore grade: %.2f %% Cu" % cu_pct[mask].mean())

mask        : [ True  True  True False  True False  True]
ore grades  : [0.79 0.83 1.2  2.1  1.75]
ore fraction: 71%
mean ore grade: 1.33 % Cu


## 3. Creating arrays — depth profiles and grids

In [4]:
depth = np.arange(0, 100, 2.0)          # 0 to 98 m every 2 m (like assay FROM)
temps = 15 + 0.03 * depth               # geothermal gradient 30 °C/km

print("depth[:5]:", depth[:5])
print("temp @ 98 m: %.2f °C" % temps[-1])

grid = np.zeros((3, 4))                 # 2-D array = the shape of a raster
print("grid shape:", grid.shape)

depth[:5]: [0. 2. 4. 6. 8.]
temp @ 98 m: 17.94 °C
grid shape: (3, 4)


## 4. 2-D arrays — a mini elevation model

In [5]:
rng = np.random.default_rng(42)
dem = 2500 + 300 * rng.random((5, 5))   # 5x5 elevation grid in metres

print(np.round(dem, 0))
print("highest cell :", dem.max().round(1), "m at index", np.unravel_index(dem.argmax(), dem.shape))
print("mean per row :", dem.mean(axis=1).round(1))

[[2732. 2632. 2758. 2709. 2528.]
 [2793. 2728. 2736. 2538. 2635.]
 [2611. 2778. 2693. 2747. 2633.]
 [2568. 2666. 2519. 2748. 2689.]
 [2727. 2606. 2791. 2768. 2734.]]
highest cell : 2792.7 m at index (np.int64(1), np.int64(0))
mean per row : [2671.8 2686.1 2692.5 2638.3 2725.3]


## 5. Useful everyday functions

In [6]:
au_gpt = np.array([1.75, 1.73, 0.20, np.nan, 3.10, 0.85])

print("nan-safe mean :", np.nanmean(au_gpt).round(3), "g/t")
print("sorted        :", np.sort(au_gpt))
print("cumulative    :", np.nancumsum(au_gpt).round(2))
print("clipped 0-2   :", np.clip(au_gpt, 0, 2))
print("percentile 75 :", np.nanpercentile(au_gpt, 75).round(2))

nan-safe mean : 1.526 g/t
sorted        : [0.2  0.85 1.73 1.75 3.1   nan]
cumulative    : [1.75 3.48 3.68 3.68 6.78 7.63]
clipped 0-2   : [1.75 1.73 0.2   nan 2.   0.85]
percentile 75 : 1.75


### ✏️ Try it
1. Build `depth = np.linspace(0, 4000, 81)` m and compute lithostatic pressure `P = rho*g*depth` with ρ=2700 kg/m³ — report P at 4 km in MPa.
2. Using the `dem` grid above, count cells above 2700 m with a boolean mask.

📚 Docs: https://numpy.org/doc/stable/